[service]
name = "authorization"

[http]
port = "8001"
secret = "paypay"

[database]
username = "root"
password=""
host = "localhost"
port = "3306"
dbname = "paypay"

[admin]
username = "administrator"
password = "12345"